<?php

class API{
	public static $API = array(
		"listBuckets"=> array(
			"method"=>"GET",
			"needBucket"=>FALSE,
			"needObject"=>FALSE,
			"signer"=>"DefaultContentTypeSigner->HeaderAuthSigner",
			"handler"=>"ErrorResponseHandler->ListBucketsHandler"
		),
		"deleteBucket"=>array(
			"method"=>"DELETE",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"signer"=>"DefaultContentTypeSigner->HeaderAuthSigner",
			"handler"=>"ErrorResponseHandler->BooleanHandler"
		),
		"deleteBucketCORS"=>array(
			"method"=>"DELETE",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"subResource"=>"cors",
			"signer"=>"DefaultContentTypeSigner->HeaderAuthSigner",
			"handler"=>"ErrorResponseHandler->BooleanHandler"
		),
		"deleteBucketCORS"=>array(
			"method"=>"DELETE",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"subResource"=>"cors",
			"signer"=>"DefaultContentTypeSigner->HeaderAuthSigner",
			"handler"=>"ErrorResponseHandler->BooleanHandler"
		),
		"createBucket"=>array(
			"method"=>"PUT",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"signer"=>"ACLSigner->DefaultContentTypeSigner->HeaderAuthSigner",
			"body"=>Array("builder"=>"LocationBuilder"),
			"handler"=>"ErrorResponseHandler->BooleanHandler"
		),
		"setBucketAcl"=>array(
			"method"=>"PUT",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"signer"=>"ACLSigner->DefaultContentTypeSigner->HeaderAuthSigner",
			"subResource"=>"acl",
			"handler"=>"ErrorResponseHandler->BooleanHandler"
		),
		"setBucketCORS"=>array(
			"method"=>"PUT",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"signer"=>"DefaultContentTypeSigner->ContentMD5Signer->HeaderAuthSigner",
			"subResource"=>"cors",
			"body"=>Array("builder"=>"CORSBuilder"),
			"handler"=>"ErrorResponseHandler->BooleanHandler"
		),
		"setBucketLogging"=>array(
			"method"=>"PUT",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"signer"=>"DefaultContentTypeSigner->HeaderAuthSigner",
			"subResource"=>"logging",
			"body"=>Array("builder"=>"BucketLoggingBuilder"),
			"handler"=>"ErrorResponseHandler->BooleanHandler"
		),
		"listObjects" => array(
			"method"=>"GET",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"signer"=>"DefaultContentTypeSigner->HeaderAuthSigner",
			"queryParams"=>array("Options->prefix","Options->delimiter","Options->marker","Options->max-keys"),
			"handler"=>"ErrorResponseHandler->ListObjectsHandler"
		),
		"getBucketCORS"=>array(
			"method"=>"GET",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"subResource"=>"cors",
			"signer"=>"DefaultContentTypeSigner->HeaderAuthSigner",
			"handler"=>"ErrorResponseHandler->GetBucketCORSHandler"
		),
		"getBucketLocation"=>array(
			"method"=>"GET",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"subResource"=>"location",
			"signer"=>"DefaultContentTypeSigner->HeaderAuthSigner",
			"handler"=>"ErrorResponseHandler->GetBucketLocationHandler"
		),
		"getBucketLogging"=>array(
			"method"=>"GET",
			"needBucket"=>TRUE,
			"needObject"=>FALSE,
			"subResource"=>"logging",
			"signer"=>"DefaultContentTypeSigner->HeaderAuthSigner",
			"handler"=>"ErrorResponseHandler->GetBucketLoggingHandler"
		)
	);
}
?>